### PR TITLE
Fixes #9 - Update the AWS Overview dashboard

### LINKED ISSUE #9: Improve the AWS Overview layout
Update the AWS Overview layout to take advantage of the latest widget types.

### PR DESCRIPTION
**Pull request by Grumblesmith**
Updating the AWS Overview dashboard

### CODE REVIEW

**Review by TheConnMan — APPROVED** [review]

**Review by rclagett — CHANGES_REQUESTED** [review]
netuitive.aws.rds.overallutilization computed metric was removed with a previous release: https://github.com/netuitive-community-packages/netuitive-packages-aws-rds#version-152

**Review by rclagett — APPROVED** [review]

**Review by rclagett — CHANGES_REQUESTED** [review]
I mistakenly approved when there weren't any new commits. Still need to remove the overall utilization metrics

**Comment by Grumblesmith** [comment]
I think this should be good to go now.

**Comment by Grumblesmith** [comment]
@rclag1126 Are any further changes needed here?

**Review by rclagett — APPROVED** [review]
Nope. LGTM.

**Pull request merged**
